services:
  elasticsearch:
    image: elasticsearch:7.17.17
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elastic

  apm-server:
    image: elastic/apm-server:7.17.17
    ports:
      - "8200:8200"
    networks:
      - elastic
    # volumes:
    #   - .\apm-server:/usr/share/apm-server
    command: --strict.perms=false

  kibana:
    image: kibana:7.17.17
    ports:
      - "5601:5601"
    networks:
      - elastic
networks:
  elastic:
    driver: bridge