services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.io/elasticsearch:7.17.17
    restart: unless-stopped
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  apm:
    container_name: apm-server
    image: docker.io/elastic/apm-server:7.17.17
    restart: unless-stopped
    volumes:
      - ./apm-server/data:/usr/share/apm-server/data
      - ./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - "8200:8200"
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: --strict.perms=false

  kibana:
    container_name: kibana
    image: docker.io/kibana:7.17.17
    restart: unless-stopped
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy

networks:
  elastic:
    driver: bridge
